### PR TITLE
Issue#272 document good settings for keepalive

### PR DESCRIPTION
**Pull request by nln42**

### CODE REVIEW

**Comment by nln42** [comment]
thx @uweschaefer

**Comment by nln42** [comment]
@uweschaefer - sry for closing this PR before it has been merged to master but unfortunately I'm not authorized to merge this pull request...

**Comment by uweschaefer** [comment]
my fault. i just added you as a contributor. i thought you ere part of team factcast in mercateo org.

**Comment by uweschaefer** [comment]
please try again.

**Comment by nln42** [comment]
still unauthorized
see MS Teams

**Comment by uweschaefer** [comment]
weird. just reviewed all repo and group settings and gave you admin permissions. please check again.

**Comment by nln42** [comment]
worked *thx*
but I'm not amused about having admin permissions to your project, consider to remove and check that issue next tuesday

**Pull request merged**
