### PR TITLE
Issue188 dependency cleanup

### PR DESCRIPTION
**Pull request by uweschaefer**

### CODE REVIEW

**Comment by mweirauch** [comment]
Some comments which I could work on, dependant on agreement and time-frame:

* module `factcast-spring-autoconfig` should be called `factcast-spring-boot-autoconfigure` if we follow the [official guidelines](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html) - it's a boot thing and no spring thing. (or at least `factcast-spring-autoconfigure` ;))
  * the packages in there renamed to: `org.factcast.spring.boot.autoconfigure`
  * we should not `@ImportConfiguration` them in the one `AutoConfiguration` because then you can't disable them explicitely if desired (think `spring.autoconfigure.exclude`) -> they should be listed separately (as a comma-separated list) in `spring.factories`
  * classes should be called `*AutoConfiguration`
  * `AutoConfiguration` should be called `FactCastAutoConfiguration` and moved to `.core` package (should also contain `@ConditionalOnMissingBean` in case somebody has a preference to override the autoconfigured beans
* `factcast-store-inmen` still has a `spring.factories` file leading to erroneous context startup as the referenced autoconfiguration class has moved (same applies to `factcast-client-cache` if I am not mistaken)

I hope I have not screwed up. Haven't looked at everything in detail. Just ping me if I shall give it a go.

**Comment by uweschaefer** [comment]
i'll rename project and package, and kill the inmem factories. just a sec...
for the rest, please take over...

**Comment by uweschaefer** [comment]
renaming done. please take over from here.

**Comment by uweschaefer** [comment]
thx. if you think this is ready, i'd consider merging into master before syncing with the sb2 branch. Do you?

**Comment by mweirauch** [comment]
Not done, yet.

**Comment by uweschaefer** [comment]
ok, fine. ping me, when it is ready, or if i could help.

**Pull request merged**
